### ISSUE TITLE
Add EPA support to VNFDs

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-schema#35]
As discussed in the [WP6 call](https://git.cs.upb.de/5gtango/generalInfo/wikis/wp6/confcalls/conf_27.04.2018) on Fri. 27th April 2018, it would be a nice benefit if the 5GTANGO SP could support [EPA](https://wiki.openstack.org/wiki/Enhanced-platform-awareness-pcie) capabilities.

George is going to provide more details about requirements for the platform etc. For our descriptors, this means that we need some additional fields to express the EPA configuration of a VNF.

I suggested to have a look at the OSM information model, because OSM already has EPA support, and I believe that it is a good idea to be more or less compatible to them.

There is an example VNF package from OSM's hackfest that has EPA enabled: https://osm-download.etsi.org/ftp/osm-3.0-three/2nd-hackfest/packages/hackfest_4_vnfd.tar.gz

The corresponding section in the VNFD is placed in the VDU section an named `guest-epa`: 

```yaml
vdu:
        -   id: mgmtVM
            name: mgmtVM
            image: hackfest3-mgmt
            count: '1'
            vm-flavor:
                vcpu-count: '1'
                memory-mb: '1024'
                storage-gb: '10'
            guest-epa:
                cpu-pinning-policy: DEDICATED
                cpu-thread-pinning-policy: PREFER
                mempage-size: LARGE
                numa-node-policy:
                    mem-policy: STRICT
                    node-cnt: '1'
                    node:
                    -   id: '1'
```
 
The corresponding definition in OSM's information model can be found [here](https://osm.etsi.org/gitweb/?p=osm/IM.git;a=blob;f=models/yang/mano-types.yang;h=ba917c0b5093827d242a2443ab39b3076b86c605;hb=HEAD#l869).

I suggest the following action to add EPA support to our descriptors:

- [ ] investigate OSM (and other, e.g., TOSCA, ETSI, OpenStack EPA APIs) information models to see what is needed
- [ ] make a list of EPA-related fields that we want to have (as a comment to this issue)
- [ ] agree on those EPA fields
- [ ] add the EPA fields to our VND schemas

Note: Even if our current platform does not support all EPA functionalities, it is still valuable that our descriptors support as many as possible.
