### ISSUE TITLE
Add "logo" field to all descriptors

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-schema#5]
This is certainly not "highly important" but still nice to have (a lot of other systems support it):

Add a (optional!) `logo` field to NSDs and VNFDs that it of type `string` and points to a logo file that is shipped with the package.

The GUIs can then make use of it and display it in the list of on-boarded or instantiated services / VNFs, e.g., the logo of the VNF vendor.

The package descriptors will support it as well.

Example:
```yaml
vendor: "eu.5gtango"
name: "example-package"
version: "0.1.1"
maintainer: "Manuel Peuster, Paderborn University"
release_data_time: "2017.01.01T10:00+03:00"  # IETF RFC3339
description: "This is an example 5GTANGO package."
logo: "icons/upb_logo.png"  # path to logo file (PNG or JPEG)
```
