### ISSUE TITLE
Support multiple images in VNF Descriptors

### ISSUE THREAD

**Issue by peerh** [sonata-nfv/tng-schema#67]
Some background discussion from email between Manuel and Peer:

if I remember right, it is not possible right now. There is a field for the image_type but one can only specify a single image per VDU.

But we can add the possibility to have more images with different types in there. In fact, I think OSM recently introduced something similar to support OpenStack and vWare deployments with different images. They call it “alternative_image” or so.

I think the 5GPICTURE project works on similar things under the umbrella of “multi version VNFs”: Have one VNFs for x86, have one for x86 with attached FPGA or GPU accelerator, have one VNF for a small ARM chip on a switch, etc.

Adding it to the descriptors is easy. But our IA and SP guys have to support it. I would say we should add it to the TODOs for the time after v4.0, no?

One thing to keep in mind is that if such a field exists, V&V results need to reference the image that was used in testing, as the results may and will vary depending on the selected architecture and image.

Something like:

* images:
  * image: “the name or id  or url of the image”
    * image_type: qcow2
    * image_arch: x86
  * image: “the name or id  or url of the image”
    * image_type: qcow2
    * image_arch: arm
  * image: “the name or id  or url of the image”
    * image_type: docker
    * image_arch: x86

**Comment by mpeuster** [comment]
A suggestion would be to keep the existing fields: `image:string` and add an additional list called `alternative_images` to the VNFD. With this we would stay backward compatible.

Future versions of the SP could the look into this `alternative_images` if they support it.


Example
```yaml
image: old_image_value  # default as it is today
image_type: qcow2

alternative_images:  # optional extension
  - image: “the name or id or url of the image”
    image_type: qcow2
    image_arch: x86
  - image: “the name or id or url of the image”
    image_type: qcow2
    image_arch: arm
  - image: “the name or id or url of the image”
    image_type: docker
    image_arch: x86

```

Disclaimer: This is how OSM did it to support different images for OpenStack vs. VIO vs. Amazon

What do you think?
