### ISSUE TITLE
Allow QoS properties for virtual links (VLDs)

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-schema#81]
We need this for the communication pilot.
It seems parts of this is already implemented, so at least do a cross check.

Something like:

```yaml
properties:  # (arbitrary key/value list for each link)
   qos:
     latency: value 
     bw: value
```
